### ISSUE TITLE
Running server failing - note-controller not comitted?

### ISSUE THREAD

**Issue by Noitidart** [1yzo/value-life-foundation-donate#1]
I cloned, installed `nodemon` globally, did `npm i`, then `npm start` but it fails for `Error: Cannot find module '../controllers/note-controller'` full error below. Did you not commit `note-controller`?

```
PS C:\Users\Mercurius\Documents\GitHub\value-life-foundation-donate> npm start

> react-create-app-express-boiler@1.0.0 start C:\Users\Mercurius\Documents\GitHub\value-life-foundation-donate
> nodemon ./server/index.js

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./server/index.js`
module.js:491
    throw err;
    ^

Error: Cannot find module '../controllers/note-controller'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Mercurius\Documents\GitHub\value-life-foundation-donate\server\routes\index.js:4:24)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Noitidart** [comment]
npm start in client is working, and mashallah man this is really good. its not yet responsive though.

**Comment by 1yzo** [comment]
yeah haha I didnt touch the server part yet I just been working in the client folder

**Comment by Noitidart** [comment]
why "haha"?
